name: Contiuos Integration app-capputeeno

on:
    push:
      branches:
        - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      - name: run test
        run: |
          yarn install
          yarn test
